### ISSUE TITLE
Need 2.1.1 released to maven central

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/common-annotations-api#106]
The 2.1.1 API has been staged:
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/annotation/jakarta.annotation-api/2.1.1/

But the following job needs to be run with jakartaannotation-1012 as the VERSION parameter to release this to maven central:
https://jakarta.oss.sonatype.org/service/local/staging/deployByRepositoryId

**Comment by lukasj** [comment]
it's there
