### ISSUE TITLE
Release 1.3.4 to maven central

### ISSUE THREAD

**Issue by michaelhixson** [eclipse-ee4j/common-annotations-api#29]
It looks like you all tried to release jakarta.annotation-api 1.3.4 to maven central but the release got stuck in staging.  Can you complete the release?

I noticed this because I tried to use the latest release of hk2, and it's broken because it depends on jakarta.annotation-api 1.3.4.  https://github.com/eclipse-ee4j/glassfish-hk2/issues/432

**Comment by Tomas-Kraus** [comment]
https://jenkins.eclipse.org/ca/job/ca-api-release-finalize job was modified to release aartifacts to central.
Release job passed: https://jenkins.eclipse.org/ca/job/ca-api-release-finalize/17/console
Created PRs to merge release info into EE4J_8 branch:
- https://github.com/eclipse-ee4j/common-annotations-api/pull/30
- https://github.com/eclipse-ee4j/common-annotations-api/pull/31

**Comment by Tomas-Kraus** [comment]
Done, can be closed.
