### ISSUE TITLE
The jakarta.annotation-api.jar should go under modules/endorsed in Web Profile

### ISSUE THREAD

**Issue by bhatpmk** [eclipse-ee4j/common-annotations-api#32]
In the Eclipse GlassFish Web Profile, I can see jakarta.annotation-api.jar under glassfish/modules, where as the same jar is available under glassfish/modules/endorsed in Full Profile. This change in the location of the jar is resulting in signature test failure.

**Comment by vinayvishal** [comment]
PR https://github.com/eclipse-ee4j/glassfish/pull/22706 raised.

**Comment by vinayvishal** [comment]
PR merged. @bhatpmk, I am unable to close the issue.
