### ISSUE TITLE
Update Scope Statement for Jakarta Common Annotations Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/common-annotations-api#33]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by rotty3000** [comment]
Here's my first crack at this:

> **Jakarta Annotations** provides a specification document, TCK and a collection 
of annotations representing common semantic concepts in the Java SE and Java EE 
platforms whoes goal is to enable a declarative style of programming that 
applies across a variety of Java(TM) technologies.

**Comment by rotty3000** [comment]
Is it still appropriate to mention `Java SE`?

**Comment by smillidge** [comment]
Java EE probably needs to be changes to Jakarta EE?

**Comment by waynebeaton** [comment]
If I boil it down to the specification itself, and tweak a little, I end up with this:

> Jakarta Annotations defines a collection of annotations representing common semantic concepts that enable a declarative style of programming that applies across a variety of Java technologies.

IMHO, it's enough to say "Java technologies" without calling out EE and SE specifically. FWIW, it's not required to include (TM).

I'm concerned that it's a little too "hand-wavy". Is it possible to better define "semantic concepts"?

**Comment by ivargrimstad** [comment]
Go with this:

Jakarta Annotations defines a collection of annotations representing common semantic concepts that enable a declarative style of programming that applies across a variety of Java technologies.

**Comment by rotty3000** [comment]
> I'm concerned that it's a little too "hand-wavy". Is it possible to better define "semantic concepts"?

Well, the fact is that this project contains a set of somewhat unrelated annotations.
* Security annotations (`javax.annotation.security.*`)
* annotation indicated generated code `@Generated`
* hopefully defunct DI annotation for JSF `@ManagedBean`
* widely used DI event annotations `@PostConstruct`, `@PreDestroy`
* JNDI binding DI annotations `@Resource(s)`

While the focus is largely DI, that is not the limit of the scope. So pinning this down in one sentence beyond _hand-waviness_ will be rather tricky.

**Comment by rotty3000** [comment]
I've updated the PR with the suggested wording.
