### ISSUE TITLE
Change project name to Jakarta Annotations

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/common-annotations-api#34]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
How about skipping Common and use **Jakarta Annotations**?

**Comment by rotty3000** [comment]
Yeah sounds good. I will try to take a crack at these changes on the weekend.

**Comment by Cousjava** [comment]
**Jakarta Annotations** would make me think that this includes all annotations used in Jakarta, whereas Jakarta Common Annotations makes it clear that these are annotations used in more that one place.

**Comment by rotty3000** [comment]
... Fair point.

**Comment by bshannon** [comment]
I think Jakarta Annotations is fine, and it avoids the possibility of another "JCA" acronym.

**Comment by rotty3000** [comment]
For the Github project name change, do we need to keep the -api suffix?

**Comment by bshannon** [comment]
We're going to end up with a number of GitHub repositories associated with a project.
We might have annotations-spec, annotations-api, annotations-tck, for example.
Perhaps one of them should drop the suffix.  I would argue that that should probably
be the specification project, which would result in a cleaner GitHub pages URL at
which to host the web site with all the information about the project.

**Comment by rotty3000** [comment]
makes sense!

**Comment by rotty3000** [comment]
Take a look at the associated PR for the exact wording I've come up with and comment.
