### ISSUE TITLE
Dual Licence

### ISSUE THREAD

**Issue by ChandrachudIngale** [eclipse-ee4j/common-annotations-api#35]
Hi Team,

Would like to understand the details about: Dual licensing
I see the library is : CDDL v1.1 and GPL v2 with CPE

How does it affect our usage, is the licence having specific year boundaries e.g. Year till 199 etc. please help

Appreciate your help, Thanks in advance.

**Comment by rotty3000** [comment]
You (or your organization) chooses one of the two options you wish to license under.

There are no year boundaries to my knowledge. Note **IANAL** and so you should consult one to understand the effect either choice will have on your organization.
