### ISSUE TITLE
activate travis in main repo

### ISSUE THREAD

**Issue by rotty3000** [eclipse-ee4j/common-annotations-api#47]
I don't have permission in the `eclipse-ee4j` github organization to activate the travis integration on this repo.

https://travis-ci.org/organizations/eclipse-ee4j/repositories

Can someone please enable this?

**Comment by rotty3000** [comment]
@lukasj would you know anything about this?

**Comment by lukasj** [comment]
file a bug, you can use https://bugs.eclipse.org/bugs/show_bug.cgi?id=532957 as a template

**Comment by rotty3000** [comment]
Perfect! thank you. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=549319
