### ISSUE TITLE
Compatibility Certification request for Apache Geronimo Annotations 1.3 (version 1.2)

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/common-annotations-api#61]
- [X] Organization Name ("Organization") and, if applicable, URL
Apache Software Foundation
- [X]   Product Name, Version and download URL (if applicable)
[Apache Geronimo Annotations 1.3 (version 1.2)](https://search.maven.org/artifact/org.apache.geronimo.specs/geronimo-annotation_1.3_spec/1.2/bundle)
- [X]   Specification Name, Version and download URL
[Jakarta Annotations 1.3](https://jakarta.ee/specifications/annotations/1.3/)
- [X]   TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta Annotations TCK 1.3.0](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-annotations-tck-1.3.0.zip) (build.name=annotations-tck-1.3.0_07-Aug-2019)
SHA256(eclipse-annotations-tck-1.3.0.zip)= ada069841408ba88378bb1813977ccdef4eb85e02097ba36de44bbd39cbd7c6c
- [X]   Public URL of TCK Results Summary
[TCK results summary](http://tomee.apache.org/tomee-8.0/docs/TCK/jakarta-annotations.html)
- [X]   Any Additional Specification Certification Requirements
None
- [X]   Java runtime used to run the implementation
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)
- [X]   Summary of the information for the certification environment, operating system, cloud, ...
Linux
- [X]   By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X]   By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by m0mus** [comment]
Accepted by lazy consensus.
