### ISSUE TITLE
Jakartizing the Spec

### ISSUE THREAD

**Issue by jeyvison** [eclipse-ee4j/common-annotations-api#65]
hey Folks!

In order to start the work to jakartize the spec, I'd like to confirm if this is the document that we should use as reference:

https://download.oracle.com/otndocs/jcp/common_annotations-1_3-mrel3-eval-spec/

If someone can confirm it, I'll start the process of jakartize it right after.

**Comment by m0mus** [comment]
No, it's wrong document. The correct document can be downloaded from here: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20974

Here is a jakartization process description:
https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc

@jeyvison Let me know if you are taking this task.

**Comment by jeyvison** [comment]
Hi @m0mus . No, I'm not. Feel free to work on it ^^
