### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/common-annotations-api#8]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Jobs:
-master: https://jenkins.eclipse.org/ca/job/ca-api-master-build/
-EE4J_8: https://jenkins.eclipse.org/ca/job/ca-api-ee4j8-build/
Both are working fine.
