### ISSUE TITLE
Compatibility Certification Request for Eclipse GlassFish 7.0.0-M1

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/common-annotations-api#98]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  [Eclipse GlassFish 7.0.0-M1](https://github.com/eclipse-ee4j/glassfish/releases/download/7.0.0-M1/glassfish-7.0.0-M1.zip)
- [x] Specification Name, Version and download URL\
   [Jakarta Annotations 2.1](https://jakarta.ee/specifications/annotations/2.1/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta Annotations TCK 2.1.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-annotations-tck-2.1.0.zip), SHA-256: 875811dbc18353f74ff96afb7ced8fb6b4cfa02daac07806e6701f698e3a9d4b
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-annotations/2.1/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 11
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
SHA-256 for the TCK should be `875811dbc18353f74ff96afb7ced8fb6b4cfa02daac07806e6701f698e3a9d4b`

**Comment by edbratt** [comment]
Accepting CCR via lazy consensus time-out
